services:
  - docker

install:
  - docker build -t hmmer .

script:
  - docker run hmmer hmmsearch -h
  - git clone ddiez/dataset
  - docker run -v $(pwd):/home/biodev hmmer hmmsearch dataset/hmm/Ras.hmm dataset/fasta/uniprot.fasta
