services:
  - docker

install:
  - docker build -t hmmer .

before_script:
  - git clone https://github.com/ddiez/dataset.git

script:
  - docker run hmmer hmmsearch -h
  - docker run -v $(pwd):/home/biodev hmmer hmmsearch dataset/hmm/Ras.hmm dataset/fasta/uniprot.fasta
